### ISSUE TITLE
Change the url for the last choice, touch screen watch...

### ISSUE THREAD

**Issue by markthepixel** [Firehed/firstworldproblems.biz#6]
Change the url for the last choice, touch screen watch...
from Apple to Pebble:
http://getpebble.com/

Apple decided that you liked teh watch idea so much that they would make it look like a mini nokia phone xD

**Comment by Firehed** [comment]
Pebble isn't actually a touchscreen, but I'm open to other suggestions since Apple has killed off the appropriate Nano!

**Comment by ekux44** [comment]
How about TouchTime?

http://www.kickstarter.com/projects/touchtime/touch-time-digital-watch-with-touch-screen

**Comment by markthepixel** [comment]
Oh yeah! Sorry :x 

TouchTime is prob your best bet, there is also
http://www.thinkgeek.com/product/e596/

which doesn't really work too too well xD

**Comment by Firehed** [comment]
thanks for the suggestions, we've updated it to the touchtime watch
